import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import { createFrontendServer } from '../dev-server.mjs';

const output = fileURLToPath(new URL('../test-results/',import.meta.url));
await mkdir(output,{recursive:true});
const server = createFrontendServer({apiOrigin:process.env.TEST_API_ORIGIN || ''});
await new Promise(resolve => server.listen(0,'127.0.0.1',resolve));
const origin = `http://127.0.0.1:${server.address().port}`;
const chrome = process.env.BROWSER_PATH ?? ['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(existsSync);
let browser;
try {
  browser = await chromium.launch({headless:true,...(chrome ? {executablePath:chrome} : {})});
  const context = await browser.newContext({ viewport:{width:1440,height:1050}, reducedMotion:'reduce' });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const go = async name => {
    const nav = await page.locator('.control-sidebar').isVisible() ? '.side-link' : '.tab';
    const link=page.locator(`${nav}[href="#${name}"]`); if(await link.count()) await link.click(); else await page.evaluate(view=>location.hash=view,name);
    await page.waitForSelector(`main[data-view="${name}"]`);
  };
  await page.goto(`${origin}/?map=2d#map`);
  await page.waitForSelector('#city-map');
  assert.match(await page.locator('.score-ring').innerText(),/52,56/);
  await page.screenshot({path:`${output}/home-desktop.png`,fullPage:true});
  const overflow = async () => assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth),false,'No horizontal overflow');
  await overflow();
  await go('decisions');
  await page.waitForSelector('.decision-card');
  assert.equal(await page.locator('.decision-card').count(),14);
  assert.equal(await page.locator('[data-action="calculate"]').isDisabled(),true);
  await page.locator('[data-action="filter"][data-group="T"]').click();
  assert.equal(await page.locator('.decision-card').count(),3);
  await page.locator('[data-action="filter"][data-group="all"]').click();
  await page.screenshot({path:`${output}/decisions-desktop.png`,fullPage:true});
  await go('districts');
  await page.waitForSelector('.district-grid');
  assert.equal(await page.locator('.district-card').count(),5);
  await page.locator('[data-action="district"][data-district="Нура"]').click();
  assert.equal(await page.locator('.district-indicators .metric').count(),10);
  await page.screenshot({path:`${output}/districts-desktop.png`,fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await go('map');
  await page.screenshot({path:`${output}/home-mobile.png`,fullPage:true});
  await overflow();
  await go('decisions');
  await page.locator('[data-action="pick"][data-id="M7"]').click();
  await page.waitForSelector('dialog[open]');
  await page.screenshot({path:`${output}/district-sheet-mobile.png`});
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('dialog').evaluate(el => el.open),false);
  assert.equal(await page.evaluate(() => document.activeElement?.dataset.id),'M7');
  const pick = async (id,district) => {
    await page.locator(`[data-action="pick"][data-id="${id}"]`).click();
    if (district) await page.locator(`[data-action="choose-district"][data-district="${district}"]`).click();
  };
  await pick('M7','Нура');
  await pick('M8','Нура');
  await pick('M10','Нура');
  await pick('M12');
  await pick('M5','Сарыарка');
  assert.equal(await page.locator('.selection-strip button').count(),5);
  assert.equal(await page.locator('[data-action="pick"]:not([disabled])').count(),0);
  assert.match(await page.locator('.budget-header').innerText(),/95/);
  await page.reload();
  await page.waitForSelector('.selection-strip');
  assert.equal(await page.locator('.selection-strip button').count(),5,'Draft survives reload');
  await page.locator('.budget-ready [data-action="calculate"]').click();
  await page.waitForSelector('.result-comparison');
  await page.waitForFunction(() => document.querySelector('.result-comparison strong')?.textContent === '56,54');
  await page.waitForSelector('.ai-facts');
  assert.match(await page.locator('.result-gain').innerText(),/\+3,99/);
  await page.screenshot({path:`${output}/result-mobile.png`,fullPage:true});
  await overflow();
  await page.setViewportSize({width:1440,height:1050});
  await page.screenshot({path:`${output}/result-desktop.png`,fullPage:true});
  await go('districts');
  assert.equal(await page.locator('.metric-before').count(),10);
  await page.setViewportSize({width:390,height:844});
  await page.locator('[data-action="district"][data-district="Нура"]').click();
  await page.screenshot({path:`${output}/district-detail-mobile.png`});
  await page.evaluate(() => scrollTo(0,0));
  await page.screenshot({path:`${output}/districts-mobile.png`,fullPage:true});
  await page.setViewportSize({width:320,height:740});
  for (const name of ['map','decisions','districts','result']) {
    await go(name);
    await overflow();
  }
  await page.getByRole('link',{name:'Улучшить сценарий'}).click();
  await page.locator('.plan-summary [data-action="remove"][data-id="M7"]').click();
  await go('result');
  assert.equal(await page.locator('.result-comparison').count(),0,'Editing invalidates previous score');
  assert.match(await page.locator('.empty-state').innerText(),/4 из 5/);
  // A delayed AI response from the old scenario must never replace a newer draft.
  await go('decisions');
  await page.route('**/api/analyze',async route => {
    await new Promise(resolve => setTimeout(resolve,350));
    await route.fulfill({json:{mode:'ai',explanation:'OLD_SCENARIO_ANALYSIS',summary:[]}});
  });
  await pick('M7','Нура');
  await page.locator('.budget-ready [data-action="calculate"]').click();
  await page.waitForSelector('.result-comparison');
  await page.getByRole('link',{name:'Улучшить сценарий'}).click();
  await page.locator('.plan-summary [data-action="remove"][data-id="M7"]').click();
  await page.waitForTimeout(500);
  await go('result');
  assert.equal(await page.getByText('OLD_SCENARIO_ANALYSIS').count(),0);
  // Errors must preserve calculated scores and offer an independent analysis retry.
  await page.unroute('**/api/analyze');
  await page.route('**/api/analyze', route => route.fulfill({status:503,json:{error:'Анализ временно недоступен.'}}));
  await go('decisions');
  await pick('M7','Нура');
  await page.locator('.budget-ready [data-action="calculate"]').click();
  await page.waitForSelector('[data-action="retry-analysis"]');
  assert.match(await page.locator('.result-comparison').innerText(),/56,54/);
  await page.unroute('**/api/analyze');
  await page.route('**/api/analyze', route => route.fulfill({json:{mode:'ai',explanation:'<img src=x onerror=alert(1)> Проверенный текст AI.',summary:[],recommendations:[]}}));
  await page.locator('[data-action="retry-analysis"]').click();
  await page.waitForSelector('.ai-explanation');
  assert.equal(await page.locator('.ai-explanation img').count(),0,'AI response is escaped as text');
  assert.match(await page.locator('.ai-explanation').innerText(),/<img/);
  assert.equal(await page.locator('.ai-awaiting').count(),0,'Successful AI response hides the unavailable state');
  // A failed calculation leaves all five choices available for another attempt.
  await go('decisions');
  await page.route('**/api/evaluate', route => route.fulfill({status:502,json:{error:'Расчёт временно недоступен.'}}));
  await page.locator('.budget-ready [data-action="calculate"]').click();
  await page.waitForFunction(() => !document.querySelector('.budget-ready [data-action="calculate"]')?.disabled);
  assert.equal(await page.locator('.selection-strip button').count(),5);
  assert.match(await page.locator('#toast').innerText(),/Расчёт временно/);
  assert.deepEqual(errors,[],'No browser runtime errors');
  console.log('Browser checks passed: 4 screens; desktop/390/320px; draft recovery; modal keyboard; selection; server result; stale AI protection.');
  console.log(`Screenshots: ${output}`);
} finally {
  await browser?.close();
  await new Promise(resolve => server.close(resolve));
}
