import { chromium } from 'playwright';
import { existsSync } from 'node:fs';
import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import { createFrontendServer } from '../dev-server.mjs';
const output=fileURLToPath(new URL('../test-results/',import.meta.url));
await mkdir(output,{recursive:true});
const server=createFrontendServer({apiOrigin:process.env.TEST_API_ORIGIN||''});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const origin=`http://127.0.0.1:${server.address().port}`;
const chrome=process.env.BROWSER_PATH??['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(existsSync);
let browser;
try {
  browser=await chromium.launch({headless:true,...(chrome?{executablePath:chrome}:{})});
  const page=await browser.newPage({viewport:{width:1600,height:1080},reducedMotion:'reduce'});
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(origin);
  await page.waitForSelector('#city-map');
  assert.equal(await page.locator('.district-terrain').count(),5);
  assert.match(await page.locator('.qol-instrument .score-ring').innerText(),/52,56/);
  await page.screenshot({path:`${output}/dashboard-desktop.png`,fullPage:true});
  const overflow=async()=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'No page overflow');
  const district=async name=>{await page.locator(`.map-district-selector [data-district="${name}"]`).click();await page.waitForFunction(name=>document.querySelector('.inspector-heading h2')?.textContent.trim()===name,name);};
  const layer=async key=>{await page.locator(`.map-layers [data-layer="${key}"]`).click();await page.waitForSelector(`.map-layers [data-layer="${key}"][aria-pressed="true"]`);};
  const pick=async id=>{await page.locator(`[data-action="map-pick"][data-id="${id}"]`).click();await page.waitForSelector(`.scenario-slot [data-action="remove"][data-id="${id}"]`);};
  const go=async name=>{const nav=await page.locator('.control-sidebar').isVisible()?'.side-link':'.tab';await page.locator(`${nav}[href="#${name}"]`).click();await page.waitForSelector(`${nav}[href="#${name}"][aria-current="page"]`);};
  await overflow();
  const startCamera=await page.locator('#city-map').getAttribute('viewBox');
  await page.getByRole('button',{name:'Приблизить карту'}).click();
  assert.notEqual(await page.locator('#city-map').getAttribute('viewBox'),startCamera);
  await page.getByRole('button',{name:'Показать весь город'}).click();
  assert.equal(await page.locator('#city-map').getAttribute('viewBox'),startCamera);
  await page.locator('.district-terrain[data-district="Есиль"]').focus();
  await page.keyboard.press('Enter');
  await page.waitForFunction(()=>document.querySelector('.inspector-heading h2')?.textContent.trim()==='Есиль');
  await district('Нура');await layer('S');
  await pick('M8');
  assert.match(await page.locator('.qol-instrument .score-ring').innerText(),/52,56/,'Picking a measure must not invent a new score');
  await page.locator('[data-action="map-issue"][data-issue="S1"]').click();
  await pick('M7');
  await layer('B');await page.locator('[data-action="map-issue"][data-issue="B1"]').click();await pick('M10');
  await layer('C');await pick('M12');
  await district('Сарыарка');await layer('E');await pick('M5');
  assert.equal(await page.locator('.scenario-slot.filled').count(),5);
  assert.match(await page.locator('.resource-number').innerText(),/^5/);
  await page.locator('.scenario-dock [data-action="calculate"]').click();
  await page.waitForSelector('.result-comparison');
  await page.waitForFunction(()=>document.querySelector('.result-comparison strong')?.textContent==='56,54');
  await go('home');
  assert.equal(await page.locator('[data-action="map-stage"][data-stage="after"]').getAttribute('aria-pressed'),'true');
  assert.match(await page.locator('.qol-instrument .score-ring').innerText(),/56,54/);
  assert.match(await page.locator('.critical-summary').innerText(),/0\s+критических/);
  await district('Нура');await layer('S');
  assert.match(await page.locator('.problem-list').innerText(),/Улучшено/);
  await page.screenshot({path:`${output}/dashboard-after.png`,fullPage:true});
  await page.locator('[data-action="map-stage"][data-stage="before"]').click();
  assert.match(await page.locator('.qol-instrument .score-ring').innerText(),/52,56/);
  await page.locator('[data-action="map-stage"][data-stage="after"]').click();
  for(const width of [1440,1024,768,390,320]) {
    await page.setViewportSize({width,height:900});await overflow();
    if(width===390) {await page.screenshot({path:`${output}/dashboard-mobile.png`,fullPage:true});}
  }
  await page.locator('.scenario-slot [data-action="remove"][data-id="M8"]').click();
  assert.equal(await page.locator('[data-stage="after"]').isDisabled(),true);
  assert.match(await page.locator('.qol-instrument .score-ring').innerText(),/52,56/);
  await page.reload();await page.waitForSelector('#city-map');
  assert.equal(await page.locator('.scenario-slot.filled').count(),4);
  assert.deepEqual(errors,[]);
  console.log('Dashboard checks passed: offline map, keyboard district selection, layers, zoom, 5 problem-driven measures, server result, before/after, stale-result invalidation, 1600–320px.');
} finally {await browser?.close();await new Promise(resolve=>{server.close(resolve);server.closeIdleConnections();});}
