import { chromium } from 'playwright';
import { existsSync } from 'node:fs';
import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import { createFrontendServer } from '../dev-server.mjs';
const output=fileURLToPath(new URL('../test-results/',import.meta.url));await mkdir(output,{recursive:true});
const server=createFrontendServer({apiOrigin:process.env.TEST_API_ORIGIN||''});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const origin=`http://127.0.0.1:${server.address().port}`;
const chrome=process.env.BROWSER_PATH??['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(existsSync);
let browser;
try{
  browser=await chromium.launch({headless:true,...(chrome?{executablePath:chrome}:{})});
  const page=await browser.newPage({viewport:{width:1440,height:1050},reducedMotion:'reduce'});
  const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
  await page.goto(`${origin}/?map=2d`);
  await page.waitForSelector('.welcome-page');
  assert.match(await page.locator('.mission-rules').innerText(),/100/);
  assert.match(await page.locator('h1').innerText(),/Какой город/);
  assert.equal(await page.locator('#city-map').count(),0,'The opening screen explains the mission before showing a map');
  assert.equal(requests.some(url=>url.includes('/vendor/three/')),false,'No WebGL renderer loads on the introduction');
  await page.screenshot({path:`${output}/journey-welcome-desktop.png`,fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:`${output}/journey-welcome-mobile.png`,fullPage:true});
  await page.getByRole('button',{name:'Начать управление',exact:true}).click();
  await page.waitForSelector('[data-guide-stage="problem"]');
  assert.match(await page.locator('.manage-heading h1').innerText(),/1 из 5/);
  assert.match(await page.locator('.problem-choices').innerText(),/Доступность медицины/);
  await page.setViewportSize({width:1440,height:1050});
  await page.screenshot({path:`${output}/journey-problems.png`,fullPage:true});
  const choose=async(district,issue,id)=>{
    await page.locator('[data-guide-filter]').selectOption(district);
    await page.locator(`[data-action="guide-problem"][data-district="${district}"][data-issue="${issue}"]`).click();
    await page.waitForSelector('[data-guide-stage="options"]');
    await page.locator(`[data-action="guide-pick"][data-id="${id}"]`).click();
    await page.waitForSelector('[data-guide-stage="confirmation"]');
  };
  await page.locator('[data-guide-filter]').selectOption('Нура');
  await page.locator('[data-action="guide-problem"][data-district="Нура"][data-issue="S2"]').click();
  await page.waitForSelector('[data-guide-stage="options"]');
  assert.match(await page.locator('.chosen-problem').innerText(),/35 из 100/);
  await page.screenshot({path:`${output}/journey-options.png`,fullPage:true});
  await page.locator('[data-action="guide-pick"][data-id="M8"]').click();
  await page.waitForSelector('[data-guide-stage="confirmation"]');
  assert.match(await page.locator('.confirmation-budget').innerText(),/80/);
  assert.equal(requests.some(url=>url.endsWith('/api/evaluate')),false,'A planned project does not trigger a fabricated partial Score');
  await page.screenshot({path:`${output}/journey-confirmation.png`,fullPage:true});
  await page.locator('[data-action="guide-next"]').click();
  await choose('Нура','S1','M7');await page.locator('[data-action="guide-next"]').click();
  await choose('Нура','B1','M10');await page.locator('[data-action="guide-next"]').click();
  await choose('Нура','C2','M12');await page.locator('[data-action="guide-next"]').click();
  await choose('Сарыарка','E2','M5');await page.locator('[data-action="guide-next"]').click();
  await page.waitForSelector('[data-guide-stage="review"]');
  assert.equal(await page.locator('.review-list li').count(),5);
  assert.match(await page.locator('.guide-review').innerText(),/95 из 100/);
  await page.reload();await page.waitForSelector('[data-guide-stage="review"]');
  assert.equal(await page.locator('.review-list li').count(),5,'Draft survives a reload');
  await page.screenshot({path:`${output}/journey-review.png`,fullPage:true});
  await page.locator('.guide-review [data-action="calculate"]').click();
  await page.waitForSelector('.outcome-summary');
  await page.waitForFunction(()=>document.querySelector('.result-comparison strong')?.textContent==='56,54');
  assert.match(await page.locator('.outcome-summary').innerText(),/Кому стало лучше/);
  assert.match(await page.locator('.outcome-summary').innerText(),/5 из 5 районов/);
  await page.screenshot({path:`${output}/journey-result.png`,fullPage:true});
  await page.getByRole('link',{name:'Увидеть изменения на карте'}).click();await page.waitForSelector('main[data-view="map"]');
  assert.match(await page.locator('.qol-instrument .score-ring').innerText(),/56,54/);
  await page.getByRole('link',{name:'Вернуться к решениям'}).click();await page.waitForSelector('main[data-view="play"]');
  await page.locator('.plan-summary [data-action="remove"][data-id="M8"]').click();
  await page.waitForSelector('[data-guide-stage="problem"]');
  assert.equal(await page.locator('.plan-summary li.filled').count(),4);
  await page.evaluate(()=>location.hash='result');await page.waitForSelector('main[data-view="result"]');
  assert.equal(await page.locator('.result-comparison').count(),0,'An edited plan clears old consequences');
  for(const view of ['home','play','decisions','districts','result']){
    await page.setViewportSize({width:320,height:740});await page.evaluate(view=>location.hash=view,view);await page.waitForSelector(`main[data-view="${view}"]`);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${view} fits 320px`);
  }
  await page.evaluate(()=>{localStorage.setItem('samga.frontend.scenario.v1',JSON.stringify([{id:'M3',district:'Нура'},{id:'M13',district:'Алматы'},{id:'M7',district:'Нура'},{id:'M12'}]));location.hash='play';});
  await page.reload();await page.waitForSelector('.guide-blocked');
  await page.locator('.plan-summary [data-action="remove"][data-id="M13"]').click();
  assert.ok(await page.locator('.problem-choice:not([disabled])').count()>0,'A free-form draft that exhausted the budget can be repaired');
  assert.deepEqual(errors,[]);
  console.log('Guided journey passed: mission, problem, measure comparison, five decisions, persistence, server result, understandable outcomes, optional map and 320px layout.');
}finally{await browser?.close();await new Promise(resolve=>{server.close(resolve);server.closeIdleConnections();});}
