import { Icon } from './Icon.mjs';
import { GlassTabBar } from './GlassTabBar.mjs';
import { spentBudget } from '../lib/scenario.mjs';
const links=[['home','Начало','home'],['play','Управление','decisions'],['map','Карта города','map'],['result','Итог','chart']];
const references=[['decisions','Каталог мер','grid'],['districts','Показатели','chart']];
export function ControlShell(content,state){
  const spent=spentBudget(state.choices,state.data.measures);
  const nav=items=>items.map(([id,label,icon])=>`<a href="#${id}" class="side-link ${state.view===id?'active':''}" ${state.view===id?'aria-current="page"':''}>${Icon(icon)}<span>${label}</span>${id==='play'&&state.choices.length?`<small>${state.choices.length}</small>`:''}</a>`).join('');
  const pageClass=state.view==='map'?'map-page':['home','play'].includes(state.view)?'journey-page':'detail-page';
  const title=[...links,...references].find(([id])=>id===state.view)?.[1];
  return `<div class="control-shell"><aside class="control-sidebar"><a href="#home" class="control-emblem" aria-label="SAMGA — начало"><svg viewBox="0 0 40 40" fill="none" aria-hidden="true"><path d="m7 29 13-22 13 22M12 22h16m-12 7 4-7 4 7" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/></svg></a><span class="sidebar-caption">ВАШ СЦЕНАРИЙ</span><nav aria-label="Разделы симулятора">${nav(links)}</nav><div class="sidebar-references"><span>ИНСТРУМЕНТЫ</span>${nav(references)}</div><div class="sidebar-bottom"><button class="side-link" data-action="about">${Icon('info')}<span>О модели</span></button><div class="operator-avatar" aria-label="Рабочее пространство Аслана">A</div><span class="operator-name">Аслан<span>Городской стратег</span></span></div></aside><div class="control-workspace"><header class="control-header"><a class="control-wordmark" href="#home">SAMGA<span>АКИМ НА 5 ЧАСОВ</span></a><div class="header-location">${Icon('pin')} Астана <span>Симулятор городских решений</span></div><div class="header-status"><span class="status-dot"></span> ВАШ ГОРОД. ВАШИ РЕШЕНИЯ.<button class="icon-button" data-action="about" aria-label="О симуляторе и данных">${Icon('info')}</button></div></header><div class="workspace-toolbar"><span>Аким на 5 часов <i>/</i> <strong>${title}</strong></span><span class="workspace-budget">Бюджет <b>${100-spent}</b><small> / 100 ед.</small><i></i> Решения <b>${state.choices.length}</b><small> / 5</small></span></div><main id="content" tabindex="-1" data-view="${state.view}" class="${pageClass}">${content}</main><footer class="control-footer"><span>SAMGA AI <i>·</i> Аким на 5 часов</span><span>Учебный сценарий <i>·</i> Последствия рассчитывает модель</span></footer></div></div>${GlassTabBar(state.view)}`;
}