const assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const {createApp}=await import(pathToFileURL(path.resolve('backend/server.mjs')));
 const server=createApp({mode:'demo'});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const url='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'msedge',headless:true,args:['--enable-unsafe-swiftshader']});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:950}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  // Interaction coverage is independent of external tile availability.
  await page.route('https://**/*',r=>r.abort());
  await page.goto(url);await page.waitForSelector('.decision');
  await page.waitForFunction(()=>document.querySelector('.demo-tag').textContent.includes('2 года'));
  assert.equal(await page.locator('.decision').count(),5);
  assert.match(await page.locator('#budget').textContent(),/85/);
  await page.locator('#compare').click();await page.locator('#save-hypothesis').click();await page.locator('#close-workspace').click();
  await page.locator('.decision').first().click();
  await page.getByRole('button',{name:'Линия ЛРТ Транспорт 30 ед.'}).click();
  assert.match(await page.locator('.preview-summary').textContent(),/97 \/ 100/);
  assert.match(await page.locator('#budget').textContent(),/85/);
  await page.keyboard.press('Escape');assert.match(await page.locator('#budget').textContent(),/85/);
  await page.locator('.decision').nth(1).click();await page.locator('#target-district').selectOption('Нура');
  assert.equal(await page.locator('#save-project').isDisabled(),true);assert.match(await page.locator('#action-error').textContent(),/несовместимы/i);
  await page.keyboard.press('Escape');
  await page.locator('.decision').first().click();await page.getByRole('button',{name:'Линия ЛРТ Транспорт 30 ед.'}).click();await page.locator('#save-project').click();
  await page.waitForFunction(()=>!document.querySelector('#workspace').open);
  assert.match(await page.locator('#budget').textContent(),/97/);assert.match(await page.locator('.decision').first().textContent(),/Линия ЛРТ/);
  await page.locator('.decision').nth(1).click();await page.getByRole('button',{name:'Чистое топливо Экология и озеленение 25 ед.'}).click();
  assert.equal(await page.locator('#save-project').isDisabled(),true);assert.match(await page.locator('#action-error').textContent(),/бюджет/i);
  await page.keyboard.press('Escape');
  await page.locator('#compare').click();assert.match(await page.locator('.metric-table').textContent(),/85 → 97/);
  await page.locator('#restore-hypothesis').click();await page.waitForFunction(()=>!document.querySelector('#workspace').open);
  assert.match(await page.locator('#budget').textContent(),/85/);
  await page.locator('#all-metrics').click();assert.equal(await page.locator('.metric-table>div').count(),10);await page.keyboard.press('Escape');
  await page.locator('#insights').click();await page.waitForSelector('.analysis-summary');
  assert.match(await page.locator('.analysis-summary').textContent(),/85/);
  await page.locator('#evidence-tab').click();await page.waitForSelector('.source-card');
  await page.locator('#assistant-tab').click();assert.equal(await page.locator('#assistant-question').isDisabled(),true);await page.keyboard.press('Escape');
  await page.locator('#strategy').click();await page.locator('[data-goal="cost"]').click();await page.waitForSelector('#use-suggestion',{timeout:30000});
  assert.match(await page.locator('#search-result').textContent(),/85 → 66/);
  assert.match(await page.locator('#budget').textContent(),/85/);
  await page.locator('#use-suggestion').click();await page.waitForFunction(()=>!document.querySelector('#workspace').open);
  assert.match(await page.locator('#budget').textContent(),/66/);
  assert.match(await page.locator('#outcome-note').textContent(),/показателей: 0/);
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.locator('.decision').first().click();assert.equal(await page.locator('#workspace').isVisible(),true);
  await page.locator('#save-project').scrollIntoViewIfNeeded();assert.equal(await page.locator('#save-project').isVisible(),true);await page.keyboard.press('Escape');
  await page.locator('#compare').click();assert.match(await page.locator('#workspace-title').textContent(),/Сравнение/);
  assert.deepEqual(errors,[]);
  console.log('PASS: atomic replacement, cancel, land conflict, budget overflow, compare/restore, 10 metrics, facts, evidence, disabled live AI, optimal cost 66, mobile editing and no horizontal overflow');
 }finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
