import { readFile, writeFile } from 'node:fs/promises';
const raw = JSON.parse(await readFile(new URL('../test-results/osm-extract.json',import.meta.url)));
const names = new Map([[3479876,'Есиль'],[3482819,'Алматы'],[3486954,'Сарыарка'],[8593081,'Байконур'],[20593940,'Нура']]);
// Oblique local projection preserves actual coordinates and gives the map a shallow 3D tilt.
const project = ({lon,lat}) => [550+(lon-71.5)*1318.8+(51.16-lat)*400,430+(51.16-lat)*1500];
function simplify(points,tolerance=.65) {
  if(points.length<3) return points;
  const [a,b]=[points[0],points.at(-1)]; let farthest=0,index=0;
  for(let i=1;i<points.length-1;i++) {
    const p=points[i], dx=b[0]-a[0],dy=b[1]-a[1],den=dx*dx+dy*dy;
    const t=den ? Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/den)) : 0;
    const distance=Math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dy);
    if(distance>farthest){farthest=distance;index=i;}
  }
  return farthest>tolerance ? [...simplify(points.slice(0,index+1),tolerance).slice(0,-1),...simplify(points.slice(index),tolerance)] : [a,b];
}
const pointKey=p=>`${p.lon},${p.lat}`;
function rings(members) {
  const segments=members.filter(m=>m.role==='outer'&&m.geometry?.length).map(m=>[...m.geometry]); const output=[];
  while(segments.length) {
    const ring=segments.pop();
    while(pointKey(ring[0])!==pointKey(ring.at(-1))) {
      const key=pointKey(ring.at(-1));
      const index=segments.findIndex(s=>pointKey(s[0])===key||pointKey(s.at(-1))===key);
      if(index<0) throw new Error('Unclosed OSM boundary; refusing to invent a polygon.');
      const segment=segments.splice(index,1)[0]; if(pointKey(segment[0])!==key) segment.reverse(); ring.push(...segment.slice(1));
    }
    output.push(ring);
  }
  return output;
}
const path=(points,closed=false)=>simplify(points.map(project)).map((p,i)=>`${i?'L':'M'}${p[0].toFixed(1)},${p[1].toFixed(1)}`).join('')+(closed?'Z':'');
const anchors={'Есиль':{lon:71.495,lat:51.065},'Алматы':{lon:71.607,lat:51.16},'Сарыарка':{lon:71.35,lat:51.2},'Байконур':{lon:71.506,lat:51.244},'Нура':{lon:71.315,lat:51.105}};
function inside(point,ring) {let yes=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j];if((a.lat>point.lat)!==(b.lat>point.lat)&&point.lon<(b.lon-a.lon)*(point.lat-a.lat)/(b.lat-a.lat)+a.lon)yes=!yes;}return yes;}
const districts=raw.elements.filter(e=>e.type==='relation'&&names.has(e.id)).map(e=>{
  const name=names.get(e.id),outer=rings(e.members),anchor=anchors[name];
  if(!outer.some(r=>inside(anchor,r))) throw new Error(`Label outside district: ${name}`);
  return {name,osmId:e.id,path:outer.map(r=>path(r,true)).join(''),anchor:project(anchor).map(n=>Math.round(n)),coordinates:anchor};
});
if(districts.length!==5) throw new Error('Missing model districts.');
const ways=raw.elements.filter(e=>e.type==='way'&&e.geometry?.length>1);
const map={source:'OpenStreetMap contributors',license:'ODbL-1.0',attributionUrl:'https://www.openstreetmap.org/copyright',timestamp:raw.osm3s.timestamp_osm_base,projection:'Oblique local geographic projection',districts,
  roads:ways.filter(w=>w.tags.highway).map(w=>({kind:w.tags.highway,path:path(w.geometry)})),
  water:ways.filter(w=>w.tags.waterway||w.tags.natural==='water').map(w=>({kind:w.tags.waterway||'area',path:path(w.geometry,w.tags.natural==='water')})),
  parks:ways.filter(w=>w.tags.leisure==='park').map(w=>path(w.geometry,true))
};
await writeFile(new URL('../lib/astana-geography.mjs',import.meta.url),`// OpenStreetMap contributors, ODbL 1.0. See MAP-SOURCES.md. Generated by scripts/build-map.mjs.\nexport const geography = ${JSON.stringify(map)};\n`);
console.log(JSON.stringify({districts:districts.map(d=>({name:d.name,anchor:d.anchor})),roads:map.roads.length,water:map.water.length,parks:map.parks.length,bytes:JSON.stringify(map).length}));
