import { BudgetHeader } from '../components/BudgetHeader.mjs';
import { DecisionCard } from '../components/DecisionCard.mjs';
import { Icon } from '../components/Icon.mjs';
import { esc, groupLabels } from '../lib/format.mjs';
export function Decisions(state) {
  const measures = state.data.measures.filter(m => state.group === 'all' || m.group === state.group);
  return `<header class="page-heading"><div class="eyebrow">ВАШ СЦЕНАРИЙ · ШАГ ${Math.min(5,state.choices.length+1)} ИЗ 5</div><h1>Решения для города<span class="title-dot">.</span></h1><p>Расставьте приоритеты. У каждого решения есть последствия.</p></header>${BudgetHeader(state)}
  <div class="catalog-toolbar"><div class="filters" role="group" aria-label="Направление мероприятий">${Object.entries({all:'Все',...groupLabels}).map(([key,label]) => `<button class="filter ${state.group === key ? 'active' : ''}" data-action="filter" data-group="${key}" data-focus="filter-${key}" aria-pressed="${state.group === key}">${label}</button>`).join('')}</div><span class="catalog-count">${state.data.measures.length} мероприятий</span></div>
  ${state.choices.length ? `<div class="selection-strip" aria-label="Выбранные решения"><span>Ваш выбор</span>${state.choices.map(c => `<button data-action="remove" data-id="${c.id}" ${state.busy ? 'disabled' : ''} title="Убрать решение" aria-label="Убрать: ${esc(state.data.measures.find(m => m.id === c.id).name)}">${esc(state.data.measures.find(m => m.id === c.id).name)}${c.district ? `<small> · ${esc(c.district)}</small>` : ''}${Icon('close')}</button>`).join('')}</div>` : ''}
  <div class="decisions-grid">${measures.map(m => DecisionCard(m,state)).join('')}</div><details class="rules"><summary>${Icon('info')} Как учитываются эффекты и ограничения</summary><p>Выберите ровно 5 мероприятий на сумму до 100 единиц. Не более двух мер одного направления. ЛРТ и автобусные полосы несовместимы; парк и школа, чистое топливо и модернизация сетей нельзя совмещать в одном районе.</p><p>На карточках указан полный ожидаемый эффект. Сервер учитывает задержку внедрения, синергии и исходные показатели районов. Оценка доступна после расчёта всех пяти решений.</p></details>
  <section class="calculate-panel glass-card"><div><strong>${state.choices.length === 5 ? 'Ваш сценарий готов' : `Выбрано ${state.choices.length} из 5 решений`}</strong><p>${state.choices.length === 5 ? 'Посмотрите, как изменится качество жизни.' : 'Добавьте пять мероприятий, чтобы увидеть итог.'}</p></div><button class="button primary" data-action="calculate" ${state.choices.length !== 5 || state.busy ? 'disabled' : ''}>${state.busy ? '<span class="spinner"></span> Рассчитываем…' : `Рассчитать результат ${Icon('arrow')}`}</button></section>`;
}
