import { DistrictCard } from '../components/DistrictCard.mjs';
import { GlassCard } from '../components/GlassCard.mjs';
import { MetricBar } from '../components/MetricBar.mjs';
import { Icon } from '../components/Icon.mjs';
import { esc, fmt, signed, groupLabels, groupIcons } from '../lib/format.mjs';
export function Districts(state) {
  const district = state.data.baseline.districts.find(d => d.name === state.district) ?? state.data.baseline.districts[0];
  const after = state.result?.districts.find(d => d.name === district.name);
  return `<header class="page-heading"><div class="eyebrow">ОДИН ГОРОД · РАЗНЫЕ ПРИОРИТЕТЫ</div><h1>Пять районов Астаны<span class="title-dot">.</span></h1><p>Узнайте, где изменения нужны больше всего.</p></header><div class="district-legend"><span><i class="trait-dot good"></i>Сильная сторона</span><span><i class="trait-dot concern"></i>Зона внимания</span><span class="district-source">Население — доля от города</span></div>
  <div class="district-grid">${state.data.baseline.districts.map((d,i) => DistrictCard(d,i,state)).join('')}</div>
  ${GlassCard(`<div id="district-detail" class="district-detail"><div class="district-detail-header"><div><div class="eyebrow">РАЙОН В ДЕТАЛЯХ</div><h2>${esc(district.name)}</h2><p>${esc(district.profile)}</p></div><div class="district-detail-score"><span>Общий показатель</span><strong>${after ? `<small>${fmt(district.score,1)} → </small>` : ''}${fmt(after?.score ?? district.score,1)}</strong>${after ? `<span class="positive">${signed(after.score-district.score)} после решений</span>` : '<span>Исходное состояние</span>'}</div></div><div class="metric-legend"><span>${after ? '<i></i> До решений <i class="after"></i> После решений' : '10 показателей качества городской среды'}</span><span>Шкала 0–100</span></div><div class="district-indicators">${Object.entries(groupLabels).map(([key,label]) => `<section class="indicator-group" data-group="${key}"><h3>${Icon(groupIcons[key])}${label}</h3>${state.data.indicators.filter(i => i.id.startsWith(key)).map(i => MetricBar({label:i.name,before:district.values[i.id],after:after?.values[i.id] ?? district.values[i.id],compare:Boolean(after),group:key})).join('')}</section>`).join('')}</div>${!after ? `<div class="district-next">${Icon('info')}<p>Сравнение «до → после» появится, когда вы выберете пять решений и рассчитаете результат.</p><a href="#decisions">К решениям ${Icon('arrow')}</a></div>` : `<p class="fine-print district-result-note">Показатели после решений получены из расчёта вашего сценария.</p>`}</div>`,'district-panel')}`;
}
