import { JourneyProgress } from '../components/JourneyProgress.mjs';
import { PlanSummary } from '../components/PlanSummary.mjs';
import { Icon } from '../components/Icon.mjs';
import { journeyProblems,selectedProblem,guidedReason } from '../lib/journey.mjs';
import { spentBudget } from '../lib/scenario.mjs';
import { esc,fmt,groupIcons } from '../lib/format.mjs';

function Problems(state){
  const problems=journeyProblems(state,state.guideFilter);
  const visible=state.guideAll?problems:problems.slice(0,6);
  return `<section class="guide-problems"><div class="guide-section-heading"><div><span class="journey-eyebrow">СНАЧАЛА — ПРИОРИТЕТ</span><h2>Кому поможем на этот раз?</h2><p>Выберите проблему. Затем сравним, как её можно решить.</p></div><label class="guide-district-filter"><span>Район</span><select data-guide-filter aria-label="Выбрать район">${['all',...state.data.districts.map(d=>d.name)].map(name=>`<option value="${esc(name)}" ${state.guideFilter===name?'selected':''}>${name==='all'?'Все районы':esc(name)}</option>`).join('')}</select></label></div><div class="problem-choices">${visible.map(p=>`<button class="problem-choice ${p.value<40?'critical':''}" data-action="guide-problem" data-district="${esc(p.district)}" data-issue="${p.id}" ${!p.available?'disabled':''}><div class="problem-choice-top"><span>${Icon('pin')}${esc(p.district)}</span><span class="problem-priority">${p.value<40?'Особенно важно':'Требует внимания'}</span></div><h3>${esc(p.title)}</h3><p>Показатель сейчас <b>${fmt(p.value,0)} из 100</b></p><div class="problem-choice-track"><span style="width:${p.value}%"></span></div><div class="problem-choice-bottom"><span>${!p.available?'Нет доступных мер для этого плана':p.planned?'Мера уже в плане — можно усилить':'Посмотреть варианты решения'}</span>${Icon('arrow')}</div></button>`).join('')}</div>${problems.length>6?`<button class="guide-more" data-action="guide-more">${state.guideAll?'Показать главные проблемы':`Все проблемы · ${problems.length}`} ${Icon('chevron')}</button>`:''}<p class="guide-hint">${Icon('info')} Сначала показаны низкие показатели, для которых в вашем бюджете есть решения. Меры в плане ещё не означают, что проблема решена.</p><a class="guide-map-link" href="#map">Хочу выбрать район на 3D-карте ${Icon('map')}</a></section>`;
}
function Options(state){
  const problem=selectedProblem(state),spent=spentBudget(state.choices,state.data.measures);
  const measures=state.data.measures.filter(m=>m.effects[problem.id]>0).sort((a,b)=>a.cost-b.cost);
  const names=Object.fromEntries(state.data.indicators.map(i=>[i.id,i.name]));
  return `<section class="guide-options"><button class="guide-back" data-action="guide-back">← Выбрать другую проблему</button><div class="chosen-problem"><span class="journey-eyebrow">${esc(problem.district.toUpperCase())} · ВАШ ПРИОРИТЕТ</span><h2>${esc(problem.title)}</h2><p>Сейчас — <strong>${fmt(problem.value,0)} из 100</strong>. Какую меру включим в ваш план?</p></div><div class="solution-choices">${measures.map(m=>{
    const reason=guidedReason(state,m,problem.district);
    return `<article class="solution-choice" data-measure="${m.id}"><div class="solution-choice-top"><span class="category-icon">${Icon(groupIcons[m.group])}</span><strong>${m.cost}<small> ед.</small></strong></div><h3>${esc(m.name)}</h3><p class="solution-scope">${Icon(m.type==='city'?'city':'pin')}${m.type==='city'?'Поможет всему городу':`Для района ${esc(problem.district)}`}</p><div class="solution-effects">${Object.entries(m.effects).map(([id,value])=>`<div class="${value<0?'negative':''}"><b>${value>0?'+':'−'}${Math.abs(value)}</b><span>${esc(names[id])}</span></div>`).join('')}</div><div class="solution-tradeoff"><span>${Icon('clock')} Начало эффекта — через ${m.lag} кв.</span><span>${reason?'':`После выбора останется ${100-spent-m.cost} ед.`}</span></div><button class="button primary" data-action="guide-pick" data-id="${m.id}" ${reason||state.busy?'disabled':''}>Выбрать решение ${Icon('plus')}</button>${reason?`<p class="guide-disabled-reason">${esc(reason)}</p>`:''}</article>`;
  }).join('')}</div><p class="guide-hint">${Icon('info')} Здесь показан полный ожидаемый эффект. При итоговом расчёте модель учтёт сроки внедрения и влияние других мер.</p></section>`;
}
function Confirmation(state){
  const choice=state.guideLastChoice??state.choices.at(-1),m=state.data.measures.find(m=>m.id===choice?.id);
  if(!m)return Problems(state);
  const spent=spentBudget(state.choices,state.data.measures);
  return `<section class="guide-confirmation"><span class="confirmation-mark">${Icon('check')}</span><span class="journey-eyebrow">РЕШЕНИЕ ${state.choices.length} ИЗ 5</span><h2>Приоритет выбран.</h2><p class="confirmation-description">${esc(m.name)}<span>${esc(choice.district??'Весь город')}</span></p><div class="confirmation-budget"><div><span>Стоимость меры</span><strong>${m.cost}<small> ед.</small></strong></div><div><span>Осталось в бюджете</span><strong>${100-spent}<small> ед.</small></strong></div></div><p class="confirmation-next">${state.choices.length===5?'Все пять решений приняты. Проверьте план — и узнайте, каким станет город.':`Мера добавлена в план. Теперь выберите следующий приоритет. Осталось решений: ${5-state.choices.length}.`}</p><button class="button primary" data-action="guide-next">${state.choices.length===5?'Проверить мой план':'Принять следующее решение'}${Icon('arrow')}</button><p class="guide-hint">Последствия появятся после итогового расчёта.</p></section>`;
}
function Review(state){
  const spent=spentBudget(state.choices,state.data.measures);
  return `<section class="guide-review"><span class="journey-eyebrow">ВЫ РАССТАВИЛИ ПРИОРИТЕТЫ</span><h2>Пять решений.<br>Один новый сценарий города.</h2><p>Ваш план использует <strong>${spent} из 100 единиц</strong>. Сейчас узнаем, каким районам он поможет сильнее всего и какие проблемы останутся.</p><ol class="review-list">${state.choices.map((c,index)=>{const m=state.data.measures.find(m=>m.id===c.id);return `<li><span>${index+1}</span><div><strong>${esc(m.name)}</strong><small>${esc(c.district??'Весь город')}</small></div><b>${m.cost} ед.</b></li>`;}).join('')}</ol><button class="button primary" data-action="calculate" ${state.busy?'disabled':''}>${state.busy?'<span class="spinner"></span> Рассчитываем последствия…':`Узнать, каким стал город ${Icon('arrow')}`}</button><p class="guide-hint">Хотите изменить решение? Уберите его из плана и выберите другое.</p></section>`;
}
export function Manage(state){
  const spent=spentBudget(state.choices,state.data.measures);
  const stage=state.choices.length===5&&state.guideStage!=='confirmation'?'review':state.guideStage;
  const screen={problem:Problems,options:Options,confirmation:Confirmation,review:Review}[stage]??Problems;
  return `<div class="manage-page">${JourneyProgress(1)}<header class="manage-heading"><div><span class="journey-eyebrow">ВЫ — АКИМ АСТАНЫ</span><h1>${state.choices.length===5?'Ваш план готов к проверке':`Ваше решение ${state.choices.length+1} из 5`}</h1><p>Ресурсы ограничены. Вы выбираете, что важнее для города.</p></div><div class="manage-budget"><span>Осталось</span><strong>${100-spent}<small> / 100 ед.</small></strong><div role="progressbar" aria-label="Принятые решения" aria-valuenow="${state.choices.length}" aria-valuemin="0" aria-valuemax="5">${Array.from({length:5},(_,i)=>`<i class="${i<state.choices.length?'complete':''}"></i>`).join('')}</div><span>${state.choices.length} из 5 решений</span></div></header><div class="manage-layout"><div class="manage-main" data-guide-stage="${stage}">${screen(state)}</div>${PlanSummary(state)}</div></div>`;
}
