import { JourneyProgress } from '../components/JourneyProgress.mjs';
import { Icon } from '../components/Icon.mjs';
import { CityIllustration } from '../components/CityIllustration.mjs';
import { fmt } from '../lib/format.mjs';
import { spentBudget } from '../lib/scenario.mjs';
export function Welcome(state){
  const nura=state.data.baseline.districts.find(d=>d.name==='Нура');
  const spent=spentBudget(state.choices,state.data.measures);
  return `<div class="welcome-page">${JourneyProgress(0)}<section class="welcome-hero"><div class="welcome-copy"><span class="journey-eyebrow">АКИМ НА 5 ЧАСОВ · SAMGA AI</span><h1>Какой город<br>вы оставите <em>после себя?</em></h1><p class="welcome-lead">Станьте виртуальным акимом Астаны. Выберите, какие проблемы решить первыми, — и узнайте, как ваши решения повлияют на жизнь районов.</p><div class="mission-rules"><div><strong>100</strong><span>единиц бюджета</span></div><div><strong>5</strong><span>ваших решений</span></div><div><strong>1</strong><span>город, который изменится</span></div></div><button class="button primary welcome-start" data-action="guide-start">${state.choices.length?'Продолжить управление':'Начать управление'}${Icon('arrow')}</button>${state.choices.length?`<p class="draft-note">${Icon('check')} Ваш план сохранён: ${state.choices.length} из 5 решений · использовано ${spent} ед.</p>`:'<p class="welcome-footnote">Сценарий можно пересмотреть. Каждое решение имеет свою цену.</p>'}</div><aside class="welcome-brief"><div class="brief-top"><span>АСТАНА · ИСХОДНАЯ СИТУАЦИЯ</span>${Icon('city')}</div><div class="brief-score"><span>Качество жизни сейчас</span><strong>${fmt(state.data.baseline.score)}<small> / 100</small></strong></div>${CityIllustration()}<div class="brief-problem"><span class="brief-pin">${Icon('pin')} Район Нура</span><h2>С чего начать изменения?</h2><p>Школы и доступность медицины — самые слабые показатели этого района в модели.</p><div class="brief-metrics"><div><span>Школы и детсады</span><strong>${fmt(nura.values.S1,0)}<small> / 100</small></strong></div><div><span>Первичная медпомощь</span><strong>${fmt(nura.values.S2,0)}<small> / 100</small></strong></div></div><p class="brief-question">Помочь Нуре или сначала вложиться в другой район? Решать вам.</p></div></aside></section><section class="welcome-steps" aria-label="Что вы будете делать"><div><span>01</span><h2>Найдите проблему</h2><p>Школы, транспорт, воздух или коммунальные сети — выберите, что важнее для города.</p></div><div><span>02</span><h2>Распределите бюджет</h2><p>Сравните меры по цене, эффекту и срокам. На всё сразу денег не хватит.</p></div><div><span>03</span><h2>Узнайте последствия</h2><p>Увидите, кому помог ваш план, что осталось нерешённым и как изменился общий показатель.</p></div></section><div class="welcome-note">${Icon('info')} Учебный симулятор: проблемы и показатели условные, география Астаны реальная. Это не сервис городских обращений.</div><a href="#map" class="welcome-map-link">Сначала посмотреть районы на карте ${Icon('arrow')}</a></div>`;
}
